# 本文件是 tkaimidi 的一部分
# SPDX-FileCopyrightText: 2024-2025 thiliapr <thiliapr@tutanota.com>
# SPDX-FileContributor: thiliapr <thiliapr@tutanota.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# 基本常识
TIME_PRECISION = 120  # 时间精度
VOICED_THRESHOLD = -0.1  # 静音阈值

# 模型参数
DEFAULT_PITCH_DIM_HEAD = 32
DEFAULT_PITCH_NUM_HEADS = 2
DEFAULT_PITCH_DIM_FEEDFORWARD = DEFAULT_PITCH_DIM_HEAD * DEFAULT_PITCH_NUM_HEADS * 4  # 根据经验，dim_feedforward = dim_head * num_heads * 4
DEFAULT_DIM_HEAD = DEFAULT_PITCH_DIM_HEAD * 2
DEFAULT_NUM_HEADS = DEFAULT_PITCH_NUM_HEADS * 2
DEFAULT_DIM_FEEDFORWARD = DEFAULT_DIM_HEAD * DEFAULT_NUM_HEADS * 4
DEFAULT_PITCH_CONV1_KERNEL = 9  # 音高特征编码器前馈层第一个卷积层的卷积核大小
DEFAULT_PITCH_CONV2_KERNEL = 1  # 音高特征编码器前馈层第二个卷积层的卷积核大小
DEFAULT_VARIANCE_BINS = 256  # 音高均值离散化的精细度
DEFAULT_NUM_PITCH_LAYERS = 2  # 音高特征编码器层数
DEFAULT_NUM_ENCODER_LAYERS = 4  # 编码器层数
DEFAULT_NUM_DECODER_LAYERS = 6  # 解码器层数

# 训练参数
DEFAULT_LEARNING_RATE = 4e-3  # 学习率
DEFAULT_WEIGHT_DECAY = 1e-2  # 权重衰减系数
DEFAULT_PITCH_DROPOUT = 0.2
DEFAULT_ENCODER_DROPOUT = 0.2
DEFAULT_DECODER_DROPOUT = 0.2
DEFAULT_VARIANCE_PREDICTOR_DROPOUT = 0.5
DEFAULT_ACCUMULATION_STEPS = 4  # 梯度累计步数
DEFAULT_PIANO_ROLL_LENGTH = 128  # 记录预测-目标钢琴卷帘时，最大允许的长度，超过该长度的钢琴卷帘将会被截取